version: "3.8"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doughBros_db
    ports:
      - "3307:3306"
    volumes:
      - $HOME/Desktop/dough-bros/database/usersDB.sql:/doughBrosDB/usersDB.sql