# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dough-bros-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dough-bros-ios
    pod 'FBSDKLoginKit'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'Firebase/Storage'
    pod 'FirebaseUI/Storage'
    
end
